#!/usr/bin/env pwsh
# Post-provision hook – writes src/GovernanceCouncil.Web/.env from AZD outputs

Write-Host "`n=== Post-provision: writing .env ===" -ForegroundColor Cyan

# AZD runs hooks from the azure.yaml directory (Governance-Council/)
# Use the current working directory, not $env:AZD_PROJECT_DIR which may not be set
$projectDir = Get-Location
Write-Host "  Project directory: $projectDir"

$envDir = Join-Path $projectDir "src" "GovernanceCouncil.Web"
if (-not (Test-Path $envDir)) {
    New-Item -ItemType Directory -Path $envDir -Force | Out-Null
}

$envFile = Join-Path $envDir ".env"

$content = @"
# Auto-generated by azd provision – $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
AZURE_TENANT_ID=$(if ($env:AZURE_TENANT_ID) { $env:AZURE_TENANT_ID } else { az account show --query tenantId -o tsv })
AZURE_SUBSCRIPTION_ID=$env:AZURE_SUBSCRIPTION_ID
AZURE_RESOURCE_GROUP=$env:AZURE_RESOURCE_GROUP
AZURE_AI_FOUNDRY_ENDPOINT=$env:AZURE_AI_FOUNDRY_ENDPOINT
AZURE_AI_SERVICES_ENDPOINT=$env:AZURE_AI_SERVICES_ENDPOINT
AZURE_OPENAI_ENDPOINT=$env:AZURE_OPENAI_ENDPOINT
AZURE_AI_PROJECT_NAME=$env:AZURE_AI_PROJECT_NAME
AI_SERVICES_RESOURCE_NAME=$env:AI_SERVICES_RESOURCE_NAME
COUNCIL_MODEL_PROFILE=Fast
COUNCIL_EMBEDDING_MODEL=$env:COUNCIL_EMBEDDING_MODEL
EMBEDDING_DEPLOYMENT_NAME=$env:EMBEDDING_DEPLOYMENT_NAME
COSMOS_DB_ENDPOINT=$env:COSMOS_DB_ENDPOINT
COSMOS_DB_DATABASE_NAME=$env:COSMOS_DB_DATABASE_NAME
STORAGE_ACCOUNT_NAME=$env:STORAGE_ACCOUNT_NAME
SEARCH_SERVICE_ENDPOINT=$env:SEARCH_SERVICE_ENDPOINT
SEARCH_SERVICE_NAME=$env:SEARCH_SERVICE_NAME
APPINSIGHTS_CONNECTION_STRING=$env:APPINSIGHTS_CONNECTION_STRING
KNOWLEDGE_BASE_CONNECTION_NAME=$env:KNOWLEDGE_BASE_CONNECTION_NAME
COUNCIL_GROUNDING_PROVIDER=$(if ($env:COUNCIL_GROUNDING_PROVIDER) { $env:COUNCIL_GROUNDING_PROVIDER } else { 'webiq' })
COUNCIL_BID_MODEL=$(if ($env:COUNCIL_BID_MODEL) { $env:COUNCIL_BID_MODEL } else { 'gpt-5-nano' })
WEBIQ_CONNECTION_NAME=$env:WEBIQ_CONNECTION_NAME
WEBIQ_MCP_URL=$(if ($env:WEBIQ_MCP_URL) { $env:WEBIQ_MCP_URL } else { 'https://api.microsoft.ai/v3/mcp' })
# Web IQ key for the LOCAL MAF runtime's in-proc grounding tool (Foundry mode reads it from the connection).
WEBIQ_API_KEY=$env:WEBIQ_API_KEY
"@

Set-Content -Path $envFile -Value $content -Encoding utf8NoBOM

Write-Host "  Written to: $envFile" -ForegroundColor Green
Write-Host ""

# Trust the ASP.NET Core HTTPS development certificate so https://localhost runs without browser
# warnings. Idempotent (no-op if already trusted); may show a one-time OS confirmation on first run.
Write-Host "=== Trusting ASP.NET Core HTTPS dev certificate ===" -ForegroundColor Cyan
dotnet dev-certs https --trust

Write-Host ""
Write-Host "=== Next steps ===" -ForegroundColor Yellow
Write-Host "  1. cd src/GovernanceCouncil.Web && dotnet run"
Write-Host "  2. Open https://localhost:7080"
Write-Host ""
