#!/usr/bin/env bash
# Post-provision hook – writes src/GovernanceCouncil.Web/.env from AZD outputs

set -euo pipefail

echo ""
echo "=== Post-provision: writing .env ==="

# AZD runs hooks from the azure.yaml directory (Governance-Council/)
PROJECT_DIR="$(pwd)"
echo "  Project directory: $PROJECT_DIR"

ENV_DIR="${PROJECT_DIR}/src/GovernanceCouncil.Web"
mkdir -p "$ENV_DIR"

ENV_FILE="${ENV_DIR}/.env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by azd provision – $(date '+%Y-%m-%d %H:%M:%S')
AZURE_TENANT_ID=${AZURE_TENANT_ID:-$(az account show --query tenantId -o tsv)}
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_AI_FOUNDRY_ENDPOINT=${AZURE_AI_FOUNDRY_ENDPOINT}
AZURE_AI_SERVICES_ENDPOINT=${AZURE_AI_SERVICES_ENDPOINT}
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
AZURE_AI_PROJECT_NAME=${AZURE_AI_PROJECT_NAME}
AI_SERVICES_RESOURCE_NAME=${AI_SERVICES_RESOURCE_NAME}
COUNCIL_MODEL_PROFILE=Fast
COUNCIL_EMBEDDING_MODEL=${COUNCIL_EMBEDDING_MODEL}
EMBEDDING_DEPLOYMENT_NAME=${EMBEDDING_DEPLOYMENT_NAME}
COSMOS_DB_ENDPOINT=${COSMOS_DB_ENDPOINT}
COSMOS_DB_DATABASE_NAME=${COSMOS_DB_DATABASE_NAME}
STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
SEARCH_SERVICE_ENDPOINT=${SEARCH_SERVICE_ENDPOINT}
SEARCH_SERVICE_NAME=${SEARCH_SERVICE_NAME}
APPINSIGHTS_CONNECTION_STRING=${APPINSIGHTS_CONNECTION_STRING}
KNOWLEDGE_BASE_CONNECTION_NAME=${KNOWLEDGE_BASE_CONNECTION_NAME:-}
COUNCIL_GROUNDING_PROVIDER=${COUNCIL_GROUNDING_PROVIDER:-webiq}
WEBIQ_CONNECTION_NAME=${WEBIQ_CONNECTION_NAME:-}
WEBIQ_MCP_URL=${WEBIQ_MCP_URL:-https://api.microsoft.ai/v3/mcp}
WEBIQ_API_KEY=${WEBIQ_API_KEY:-}
EOF

echo "  Written to: $ENV_FILE"
echo ""

# Trust the ASP.NET Core HTTPS development certificate (idempotent; no-op if already trusted).
# On Linux this prints a notice (manual trust may be needed); on macOS it adds it to the keychain.
echo "=== Trusting ASP.NET Core HTTPS dev certificate ==="
dotnet dev-certs https --trust || true

echo ""
echo "=== Next steps ==="
echo "  1. cd src/GovernanceCouncil.Web && dotnet run"
echo "  2. Open https://localhost:7080"
echo ""
